[Settings]
adi_file_path = D:\Ken\HamRadio\Python\DigiModeTable\wsjtx_log.adi
recent_qso_count = 16
display_times = False
display_since = True
unique_only = True
rate_window_minutes = 20

[Window]
geometry = 630x300+872+602

[recentWindow]
geometry = 300x250+1516+601
open = yes

[repeatWindow]
geometry = 300x126+1516+866
open = yes

